#!/usr/bin/env node
// generate_levels.mjs — генерирует js/levels.generated.js (уровни 21-50).
// Запуск: node scripts/generate_levels.mjs
//
// Альтернативный способ: index.html?dev=1 → Generate × N → Save × N → Download.

import { generateLevel, validateLevel } from '../js/levelGenerator.js';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

function genOne(opts) {
  for (let i = 0; i < 80; i++) {
    const lvl = generateLevel(opts);
    if (!lvl) continue;
    if (lvl.placements.length < (opts.minWords || 3)) continue;
    if (validateLevel(lvl).ok) return lvl;
  }
  return null;
}

const out = [];
let id = 21;
// 21-35: 5 букв, 3-5 слов длины 3-5.
for (let i = 0; i < 15; i++) {
  const lvl = genOne({ letterCount: 5, minWords: 3, maxWords: 5, minWordLen: 3, maxWordLen: 5, id });
  if (lvl) { out.push(lvl); id++; } else { console.error('skip 5-letter'); }
}
// 36-50: 6 букв, 3-5 слов длины 3-6.
for (let i = 0; i < 15; i++) {
  const lvl = genOne({ letterCount: 6, minWords: 3, maxWords: 5, minWordLen: 3, maxWordLen: 6, id });
  if (lvl) { out.push(lvl); id++; } else { console.error('skip 6-letter'); }
}

const banner =
  '// Auto-generated by scripts/generate_levels.mjs. Do not edit by hand.\n' +
  '// Regenerate via:  node scripts/generate_levels.mjs\n' +
  '// Or interactively via index.html?dev=1 → Generate → Save → "Download as levels.generated.js".\n\n';

const content = banner + 'export const GENERATED_LEVELS = ' + JSON.stringify(out, null, 2) + ';\n';
const target = join(__dirname, '..', 'js', 'levels.generated.js');
await writeFile(target, content);
console.log(`Wrote ${out.length} levels → ${target} (${content.length} bytes)`);
