#!/usr/bin/env node
// generate_levels.mjs — генерирует все 50 уровней (levels.js + levels.generated.js).
// Запуск: node scripts/generate_levels.mjs
//
// Каждый уровень:
//   - центральное слово ≥ 5 букв (≥ 6 для уровней 31-50)
//   - 5-12 связанных слов в кроссворде
//   - сетка ≤ 11×11 (для портретного экрана)
//
// Альтернатива: index.html?dev=1 → Generate × N → Save × N → Download.

import { generateLevel, validateLevel } from '../js/levelGenerator.js';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

function genOne(opts) {
  for (let i = 0; i < 200; i++) {
    const lvl = generateLevel(opts);
    if (!lvl) continue;
    if (lvl.placements.length < (opts.minWords || 7)) continue;
    if (validateLevel(lvl).ok) return lvl;
  }
  return null;
}

const out = [];
let id = 1;

// 1-10: 5 букв, проще (5-9 слов).
for (let i = 0; i < 10; i++) {
  const lvl = genOne({ letterCount: 5, centerWordMinLen: 5, minWords: 5, maxWords: 9, minWordLen: 3, maxWordLen: 5, maxGridDim: 9, id });
  if (lvl) { out.push(lvl); id++; } else console.error('skip 5-letter');
}

// 11-30: 6 букв, основная масса (7-12 слов).
for (let i = 0; i < 20; i++) {
  const lvl = genOne({ letterCount: 6, centerWordMinLen: 5, minWords: 7, maxWords: 12, minWordLen: 3, maxWordLen: 6, maxGridDim: 11, id });
  if (lvl) { out.push(lvl); id++; } else console.error('skip 6-letter');
}

// 31-50: 7 букв, плотные (8-12 слов).
for (let i = 0; i < 20; i++) {
  const lvl = genOne({ letterCount: 7, centerWordMinLen: 6, minWords: 8, maxWords: 12, minWordLen: 3, maxWordLen: 7, maxGridDim: 11, id });
  if (lvl) { out.push(lvl); id++; } else console.error('skip 7-letter');
}

console.log(`Generated ${out.length} levels`);

// Записываем первые 20 в levels.js (как сырые данные RAW), остальные — в levels.generated.js.
const first20 = out.slice(0, 20);
const last30 = out.slice(20);

const levelsJs =
`// levels.js — основные 20 уровней игры.
//
// Все уровни созданы через генератор (см. scripts/generate_levels.mjs) и
// прогнаны через validateLevel. Каждый имеет:
//   - центральное слово длиной ≥ 5 букв (самое длинное)
//   - кроссворд из 5-12 связанных слов
//
// bonusWords автоматически вычисляются из словаря в populateBonus.

import { DICTIONARY, normalize } from './dictionary.js';

export function canFormWord(word, letters) {
  const pool = new Map();
  for (const ch of letters) pool.set(ch, (pool.get(ch) || 0) + 1);
  for (const ch of word) {
    const cnt = pool.get(ch) || 0;
    if (cnt === 0) return false;
    pool.set(ch, cnt - 1);
  }
  return true;
}

function populateBonus(level) {
  const lettersNorm = level.letters.map(normalize);
  const main = new Set(level.mainWords.map(normalize));
  const bonus = [];
  for (const w of DICTIONARY) {
    if (w.length < 3) continue;
    if (main.has(w)) continue;
    if (canFormWord(w, lettersNorm)) bonus.push(w);
  }
  return { ...level, bonusWords: bonus };
}

const RAW = ${JSON.stringify(first20, null, 2)};

export const HAND_CRAFTED_LEVELS = RAW.map(populateBonus);
`;

const genJs =
`// Auto-generated by scripts/generate_levels.mjs. Do not edit by hand.
// Regenerate via:  node scripts/generate_levels.mjs

export const GENERATED_LEVELS = ${JSON.stringify(last30, null, 2)};
`;

const levelsPath = join(__dirname, '..', 'js', 'levels.js');
const genPath = join(__dirname, '..', 'js', 'levels.generated.js');
await writeFile(levelsPath, levelsJs);
await writeFile(genPath, genJs);
console.log(`Wrote ${levelsPath} (${levelsJs.length} bytes)`);
console.log(`Wrote ${genPath} (${genJs.length} bytes)`);
